### ISSUE TITLE
add an "x" to the bet listing for withdrawing a bet

### ISSUE THREAD

**Issue by severinwullschleger** [lucaspelloni2/dapp-tic-tac-toe#15]
the owner of the bet needs to see an x next to his bets to withdraw them. 
x should only  be shown if bet in State MISSING_X_BETTOR or MISSING_O_BETTOR

**Comment by lucaspelloni2** [comment]
done ;)

**Comment by lucaspelloni2** [comment]
TODO in SC: bettorOnXAddr should be an address and not a name

**Comment by severinwullschleger** [comment]
SC stack to small for both (address and name).. have to delete name.. but you use it for bet listing:
`                    <tr key={bet.id}>
                      <td>{bet.gameId}</td>
                      <td>{this.getElement(bet)}</td>
                      <td>
                        <Element color={'#024169'} border={'#02b8d4'}>
                          <ValueContainer>
                            <Value>
                              {Math.round(
                                this.props.web3.utils.fromWei(
                                  bet.value,
                                  'ether'
                                ) * 1000
                              ) / 1000}
                            </Value>
                            <GameIcon
                              icon={'bet'}
                              marginLeft={'auto'}
                              marginRight={'5px'}
                              height={'20'}
                            />
                          </ValueContainer>
                        </Element>
                      </td>
                      <td>{bet.bettorOnX}</td>
                      <td>{bet.bettorOnO}</td>
                      <td>{this.getButton(bet)}</td>
                      <td>{this.getWithdrawButton(bet)}</td>
                    </tr>`

**Comment by lucaspelloni2** [comment]
Can you return just the address and the provide a method (or maybe it is already there) like ```getPlayer(Address:address)``` where the name is also returned?

**Comment by severinwullschleger** [comment]
getPlayer already exists -> methods.players(address: playerAddr)

additionally there will be a new getBettorsAddresses() method similiar to getBets just with the array of betIds and two addresses array

function getBettorAddresses() public view returns (uint[] betIds, address[] bettorOnXAddr, address[] bettorOnOAddr) {
